kind: ConfigMap
apiVersion: v1
metadata:
  name: alertmanager-config
  namespace: default
data:
  config.yml: |-
    global:
    templates:
    - '/etc/alertmanager/*.tmpl'
    route:
      receiver: slack_demo
      group_by: ['alertname', 'priority']
      group_wait: 1s
      repeat_interval: 1m
 
    receivers:
    - name: slack_demo
      slack_configs:
      - api_url: https://hooks.slack.com/services/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
        channel: '#prometheus'  