apiVersion: v1
kind: Service
metadata:
  name: todo-flaskapp
  annotations:
    prometheus.io/scrape: 'true'
    prometheus.io/port:   '5000'
spec:
  selector:
    app: todo-flaskapp
  ports:
    - port: 5000
      targetPort: 5000
  type: LoadBalancer