apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo-flaskapp
spec:
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  selector:
    matchLabels:
      app: todo-flaskapp
  template:
    metadata:
      labels:
        app: todo-flaskapp
    spec:
      containers:
        - name: todo-flaskapp
          image: smrithi23/todo-app:probe
          ports:
            - containerPort: 5000
          livenessProbe:
            httpGet:
              path: /live
              port: 5000
            initialDelaySeconds: 3
            periodSeconds: 5
          readinessProbe:
            httpGet:
              path: /health
              port: 5000
            initialDelaySeconds: 0
            periodSeconds: 5
          env:
            - name: MONGO_URL
              value: mongodb://mongo:27017/todoapp
            - name: MONGO_HOST
              value: mongo
            - name: MONGO_PORT
              value: '27017'
            - name: FLASK_ENV
              value: development
            - name: PORT
              value: '5000'
          imagePullPolicy: Always