version: '3'
services:
  flask-app:
    image: smrithi23/todo-app:latest
    ports:
      - "8000:5000"
    depends_on:
      - mongodb
    environment:
      MONGO_HOST: "mongodb:27017"
  mongodb:
    image: mongo:4.4
    ports:
      - "27017:27017"
    volumes:
      - ./mongodb-data:/data/db
volumes:
  mongodb-data: